apiVersion: batch/v1
kind: CronJob
metadata:
  name: stepcd
spec:
  schedule: "*/2 * * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        spec:
          restartPolicy: Never
          serviceAccountName: gitops
          containers:
            - name: zad2gitops 
              image: adamos321/zad2gitops
              command: [sh, -e, -c]
              args:
                - git clone https://github.com/AdamPiechowiak/zad2-config-repo /tmp/zad2-config-repo && find /tmp/zad2-config-repo -name '*.yaml' -exec kubectl apply -f {} \;
